<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Drop existing foreign keys dynamically to bypass MySQL naming conventions manually generated by SQL dump
        $fkNames = \Illuminate\Support\Facades\DB::select("SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'kiosks' AND COLUMN_NAME = 'school_id' AND CONSTRAINT_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL");
        foreach ($fkNames as $fk) {
            \Illuminate\Support\Facades\DB::statement("ALTER TABLE kiosks DROP FOREIGN KEY " . $fk->CONSTRAINT_NAME);
        }

        Schema::table('kiosks', function (Blueprint $table) {

            $table->renameColumn('school_id', 'owner_school_id');
            $table->foreign('owner_school_id')->references('id')->on('schools')->onDelete('cascade');
        });

        Schema::create('kiosk_school', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('kiosk_id');
            $table->unsignedBigInteger('school_id');
            $table->timestamps();

            $table->foreign('kiosk_id')->references('id')->on('kiosks')->onDelete('cascade');
            $table->foreign('school_id')->references('id')->on('schools')->onDelete('cascade');

            $table->unique(['kiosk_id', 'school_id']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('kiosk_school');

        Schema::table('kiosks', function (Blueprint $table) {
            $table->dropForeign(['owner_school_id']);
            $table->renameColumn('owner_school_id', 'school_id');
            $table->foreign('school_id')->references('id')->on('schools')->onDelete('cascade');
        });
    }
};
